FROM transfer

WORKDIR /app

ENV FLASK_APP=server.py

# Copy files to container
COPY transferEngine transferEngine
COPY model.tf model.tf
COPY server.py server.py

EXPOSE 5000

# Run the training script
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
